#include "Image.h"

#include <QImage>
#include <QColor>


Image::Image()
{
    initCountries();
}

QString Image::country(int x, int y)
{
    QRgb color = pixel(x, y);
    int gray = qGray(color);
    return countries.value(gray, "EMPTY");
}

void Image::initCountries()
{
    countries = QStringList({
        "Afghanistan",
        "Albania",
        "Algeria",
        "Andorra",
        "EMPTY",
        "Angola",
        "EMPTY",
        "Antarctica",
        "Argentina",
        "EMPTY",
        "Armenia",
        "EMPTY",
        "Australia",
        "Austria",
        "Azerbaijan",
        "EMPTY",
        "Bahrain",
        "Bangladesh",
        "Belarus",
        "EMPTY",
        "Belgium",
        "EMPTY",
        "EMPTY",
        "Belize",
        "Benin",
        "EMPTY",
        "Bhutan",
        "Bolivia",
        "EMPTY",
        "Bosnia and Herzegovina",
        "Botswana",
        "EMPTY",
        "EMPTY",
        "Brazil",
        "EMPTY",
        "Bulgaria",
        "Burkina",
        "Burma",
        "EMPTY",
        "Burundi",
        "EMPTY",
        "CAR",
        "Cambodia",
        "Cabinda",
        "Cameroon",
        "EMPTY",
        "Canada",
        "Chad",
        "EMPTY",
        "EMPTY",
        "Chile",
        "China",
        "Colombia",
        "EMPTY",
        "Congo",
        "EMPTY",
        "Costa Rica",
        "Cote d'Ivoire",
        "Croatia",
        "EMPTY",
        "Cuba",
        "Cyprus",
        "EMPTY",
        "Czech Republic",
        "Denmark",
        "Djibouti",
        "EMPTY",
        "Dominican Republic",
        "Ecuador",
        "EMPTY",
        "Egypt",
        "El Salvador",
        "EMPTY",
        "Equatorial Guinea",
        "Eritrea",
        "EMPTY",
        "Ethiopia",
        "Estonia",
        "Falkland Islands",
        "EMPTY",
        "Fiji",
        "Finland",
        "EMPTY",
        "France",
        "French Guiana",
        "EMPTY",
        "EMPTY",
        "Gabon",
        "EMPTY",
        "Georgia",
        "Germany",
        "Ghana",
        "EMPTY",
        "EMPTY",
        "Gibraltar",
        "Greece",
        "Greenland",
        "EMPTY",
        "Guatemala",
        "Guinea",
        "Guinea-Bissau",
        "EMPTY",
        "Guyana",
        "EMPTY",
        "Haiti",
        "Honduras",
        "Hungary",
        "EMPTY",
        "Iceland",
        "India",
        "EMPTY",
        "Indonesia",
        "Iran",
        "EMPTY",
        "Iraq",
        "Ireland",
        "Israel",
        "Italy",
        "EMPTY",
        "Jamaica",
        "EMPTY",
        "Japan",
        "Jordan",
        "EMPTY",
        "Kazakhstan",
        "Kenya",
        "EMPTY",
        "Kuwait",
        "Kyrgyzstan",
        "EMPTY",
        "Laos",
        "Latvia",
        "EMPTY",
        "Lebanon",
        "Liberia",
        "EMPTY",
        "Libya",
        "EMPTY",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Macedonia",
        "EMPTY",
        "Madagascar",
        "Malawi",
        "EMPTY",
        "EMPTY",
        "Malaysia",
        "Mali",
        "Mauritania",
        "Mexico",
        "Moldova",
        "EMPTY",
        "Monaco",
        "EMPTY",
        "Mongolia",
        "Morocco",
        "Mozambique",
        "EMPTY",
        "Namibia",
        "Nepal",
        "Netherlands",
        "EMPTY",
        "EMPTY",
        "New Zealand",
        "Nicaragua",
        "Niger",
        "EMPTY",
        "Nigeria",
        "EMPTY",
        "North Korea",
        "Norway",
        "Oman",
        "EMPTY",
        "Pakistan",
        "Panama",
        "Papua New Guinea",
        "EMPTY",
        "Paraguay",
        "Peru",
        "EMPTY",
        "Philippines",
        "Poland",
        "EMPTY",
        "Portugal",
        "Puerto Rico",
        "EMPTY",
        "Qatar",
        "Romania",
        "EMPTY",
        "EMPTY",
        "Russia",
        "Rwanda",
        "Saudi Arabia",
        "San Marino",
        "Senegal",
        "EMPTY",
        "Serbia and Montenegro",
        "Sierra Leone",
        "EMPTY",
        "EMPTY",
        "Singapore",
        "Slovakia",
        "Slovenia",
        "Somalia",
        "South Africa",
        "EMPTY",
        "EMPTY",
        "Lesotho",
        "South Korea",
        "Sri Lanka",
        "Spain",
        "Sudan",
        "EMPTY",
        "Suriname",
        "EMPTY",
        "Swaziland",
        "EMPTY",
        "Sweden",
        "Switzerland",
        "Syria",
        "EMPTY",
        "Taiwan",
        "EMPTY",
        "Tajikistan",
        "Tanzania",
        "Thailand",
        "EMPTY",
        "Togo",
        "Tunisia",
        "Turkmenistan",
        "Turkey",
        "UAE",
        "EMPTY",
        "EMPTY",
        "United Kingdom",
        "USA",
        "EMPTY",
        "Uganda",
        "Ukraine",
        "EMPTY",
        "Uruguay",
        "Uzbekistan",
        "EMPTY",
        "EMPTY",
        "Venezuela",
        "Vietnam",
        "Western Sahara",
        "Yemen",
        "EMPTY",
        "Zaire",
        "EMPTY",
        "Zambia",
        "Zimbabwe",
        "EMPTY",
        "EMPTY"
    });
}
